
if &compatible
  set nocompatible
endif

" set tgc

let s:path=expand('<sfile>:p:h')

" let g:vimpath=s:path
if has('nvim')
  let g:vimpath = "~/.nvim"
else
  let g:vimpath = "~/.vim"
endif
" let g:bundlepath = "~/lib/gu.vim"

exec 'set runtimepath+=' . s:path

filetype off

let g:mycfgfile = s:path . '/my_configs.vim'

" for s:cfg in [ 'basic', 'plugins', 'maps', 'filetypes', 'extended']
for s:cfg in [ 'basic', 'plugins', 'maps', 'extended']
  try
    exec 'source' . s:path . '/config/' . s:cfg . '.vim'
  catch
    echom 'err when executed ' . s:cfg
    echom v:exception
  endtry
endfor


set encoding=utf-8
"set langmenu=zh_CN.UTF-8
"language message zh_CN.UTF-8
" set fileencodings=utf-8,chinese,latin-1
set fileencodings=ucs-bom,utf-8,utf-16,chinese,gbk,big5,gb18030,euc-cn,latin1
if has("win32")
  set fileencoding=chinese
else
  set fileencoding=utf-8
endif

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

" colorscheme xcode-default
" colorscheme gruvbox
" set background=light
" let g:airline_theme='sol'

if has('termguicolors')
  set termguicolors
endif

if has("gui_running")
  colorscheme seagull
elseif OSX()
  set background=dark
  colorscheme gruvbox
  let g:airline_theme='dark'
else
  colorscheme onedark
  " colorscheme monokai
  let g:airline_theme='badwolf'
  " let g:airline_theme='dark'
  " let g:airline_theme='onedark'
  hi Normal ctermbg=None
endif
" colorscheme lucius
" let g:airline_theme = 'sol'

" vim: set ft=vim sw=2 ts=2 et foldmethod=marker:
